defaults:
  - _self_
  - machine: fidis
  - task: henry
  - zeo_params: co2

mode: post
  
cif_dir: /home/xiazhang/cifs_reservoir/md_cifs #/scratch/xiazhang/md_cifs_co2_3_cif
out_dir: /scratch/xiazhang/md_cifs_co2 # /scratch/xiazhang/md_cifs_co2_1bar #/scratch/xiazhang/md_cifs_co2
