defaults:
  - _self_
  - machine: lsmosrv
  - task: gcmc
  - zeo_params: co2

mode: prep
  
cif_dir: /home/xiazhang/utils/AutoMolsim/test_cif #co2_1bar_cifs # /home/xiazhang/cifs_reservoir/md_cifs #/scratch/xiazhang/md_cifs_co2_3_cif
out_dir: /home/xiazhang/utils/AutoMolsim/test_out #md_cifs_co2_1bar_jed # /scratch/xiazhang/md_cifs_co2_1bar #/scratch/xiazhang/md_cifs_co2
