defaults:
  - _self_
  - machine: local
  - task: nvt

cif_dir: /home/xiaoqi/molsim/nature_cif_deduplicated
out_dir: /home/xiaoqi/molsim/co2_nvt_deduplicated

#cif_dir: ./test_cif
#out_dir: ./test_out